name: Build
on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
        include:
          - os: windows-2019
            name: windows
          - os: ubuntu-18.04
            name: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          if [ "$RUNNER_OS" == "Windows" ]; then
            cl.exe //LD //Fe:skip-hle-nwm-wlan-comm-id-check.dll plugin.c
          else
            gcc plugin.c -shared -o skip-hle-nwm-wlan-comm-id-check.so
          fi
      - name: Prepare to upload artifact
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          mkdir artifact
          if [ "$RUNNER_OS" == "Windows" ]; then
            cp skip-hle-nwm-wlan-comm-id-check.dll artifact/
          else
            cp skip-hle-nwm-wlan-comm-id-check.so artifact/
          fi
          cp license.txt artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{matrix.name}}
          path: artifact
